import os

from dotenv import load_dotenv

load_dotenv()


APP_ENV = os.getenv("APP_ENV", "development")
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://contentuser:contentpass@postgres:5432/contentdb",
)
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
APP_SECRET_KEY = os.getenv("APP_SECRET_KEY", "dev-insecure-change-me")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "10080"))
BOOTSTRAP_ADMIN_EMAIL = os.getenv("BOOTSTRAP_ADMIN_EMAIL", "admin@example.com")
BOOTSTRAP_ADMIN_PASSWORD = os.getenv("BOOTSTRAP_ADMIN_PASSWORD", "admin12345")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-mini")
OPENAI_MAX_OUTPUT_TOKENS = int(os.getenv("OPENAI_MAX_OUTPUT_TOKENS", "1600"))
OPENAI_VERBOSITY = os.getenv("OPENAI_VERBOSITY", "low")
OPENAI_REASONING_EFFORT = os.getenv("OPENAI_REASONING_EFFORT", "minimal")
OPENAI_DAILY_REQUEST_LIMIT = int(os.getenv("OPENAI_DAILY_REQUEST_LIMIT", "20"))
OPENAI_ADMIN_DAILY_REQUEST_LIMIT = int(os.getenv("OPENAI_ADMIN_DAILY_REQUEST_LIMIT", "100"))
OPENAI_CARROSSEL_REQUEST_LIMIT = int(os.getenv("OPENAI_CARROSSEL_REQUEST_LIMIT", "3"))
OPENAI_IMAGE_MODEL = os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1-mini")
OPENAI_IMAGE_SIZE = os.getenv("OPENAI_IMAGE_SIZE", "1024x1536")
OPENAI_IMAGE_DAILY_REQUEST_LIMIT = int(os.getenv("OPENAI_IMAGE_DAILY_REQUEST_LIMIT", "21"))
OPENAI_IMAGE_ADMIN_DAILY_REQUEST_LIMIT = int(os.getenv("OPENAI_IMAGE_ADMIN_DAILY_REQUEST_LIMIT", "100"))
OPENAI_IMAGE_CARROSSEL_REQUEST_LIMIT = int(os.getenv("OPENAI_IMAGE_CARROSSEL_REQUEST_LIMIT", "7"))
OPENAI_ADMIN_IMAGE_RENDER_MAX_ATTEMPTS = int(os.getenv("OPENAI_ADMIN_IMAGE_RENDER_MAX_ATTEMPTS", "4"))
STORAGE_PATH = os.getenv("STORAGE_PATH", "/app/storage")
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "")
MEDIA_RETENTION_DAYS = int(os.getenv("MEDIA_RETENTION_DAYS", "30"))
